openapi: 3.0.0
info:
  title: Dealers Docs
  version: 1.0.0
servers:
  - url: http://localhost:8100/api/
paths:
  /examples:
    get:
      tags:
        - example
      summary: Example path
      description: Returns list of Dealers
      responses:
        '200':
          description: List of Dealers
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: string
                    exmaple: "List of dealers"
                      
                  
        '404':
          description: Route not founed